const allProjects = [
        {
                id: 1,
                projectName: 'cke',
                projectNickname: 'CKE',
                projectPath: 'assets/MP4/KK_CK_ETERNITY_BW_BG.mp4',
                vimeoPath: 'https://player.vimeo.com/video/1085210743?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479',
                typeoutName: 'CALVIN KLEIN ETERNITY',
                typeout1: 'Fashion + Luxury',
                typeout2: '2025',
},      
        {
                id: 2,
                projectName: 'marc',
                projectNickname: 'MARC',
                projectPath: 'assets/MP4/MARC JACOBS.mp4',
                vimeoPath: 'https://player.vimeo.com/video/1013672752?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479',
                typeoutName: 'MARC JACOBS SS23',
                typeout1: 'Fashion + Luxury',
                typeout2: '2023',
}, 
        {
                id: 3,
                projectName: 'bose',
                projectNickname: 'BOSE',
                projectPath: 'assets/MP4/BOSE.mp4',
                vimeoPath: 'https://player.vimeo.com/video/925403898?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479',
                typeoutName: 'BOSE X COCO GAUFF',
                typeout1: 'Campaign',
                typeout2: '2024',  
},
        {
                id: 4,
                projectName: 'contraluz',
                projectNickname: 'cz',
                projectPath: 'assets/MP4/CONTRALUZ.mp4',
                vimeoPath: 'https://player.vimeo.com/video/925424364?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479',
                typeoutName: 'CONTRALUZ',
                typeout1: 'Food & Beverage',
                typeout2: '2023',
},
        {
                id: 5,
                projectName: 'mejuri',
                projectNickname: 'MEJURI',
                projectPath: 'assets/MP4/KK_MK_MEJURI_BW_BG.mp4',
                vimeoPath: 'https://player.vimeo.com/video/1129489821?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479',
                typeoutName: "MEJURI WOMEN’S DAY",
                typeout1: 'Fashion + Luxury',
                typeout2: '2025',
},
        {
                id: 6,
                projectName: 'futureland',
                projectNickname: 'FL',
                projectPath: 'assets/MP4/FUTURELAND.mp4',
                vimeoPath: 'https://player.vimeo.com/video/786053616?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479',
                typeoutName: 'FUTURELAND',
                typeout1: 'Creative Advertisement',
                typeout2: '2022',  
},
        {
                id: 7,
                projectName: 'kors',
                projectNickname: 'KORS',
                projectPath: 'assets/MP4/KK_MK_DUAL_BOTTLE_BW_BG.mp4',
                vimeoPath: 'https://player.vimeo.com/video/1096893720?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479',
                typeoutName: "MICHAEL KORS EAU DE PARFUM",
                typeout1: 'Fashion + Luxury',
                typeout2: '2025',
},
        {
                id: 8,
                projectName: 'ysl',
                projectNickname: 'YSL',
                projectPath: 'assets/MP4/LNX REBEL.mp4',
                vimeoPath: 'https://player.vimeo.com/video/1012646511?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479',
                typeoutName: "YSL LNX REBEL",
                typeout1: 'Fashion + Luxury',
                typeout2: '2024',
},
        {
                id: 9,
                projectName: 'adidas',
                projectNickname: 'ad',
                projectPath: 'assets/MP4/ADIDAS.mp4',
                vimeoPath: 'https://player.vimeo.com/video/1013677740?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479',
                typeoutName: 'ADIDAS X TRAE YOUNG',
                typeout1: 'Campaign',
                typeout2: '2024',
},
        {
                id: 10,
                projectName: 'bae',
                projectNickname: 'BAE',
                projectPath: 'assets/MP4/KK_AE_BOSE_BW_BG.mp4',
                vimeoPath: 'https://player.vimeo.com/video/1072707069?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479',
                typeoutName: "BOSE X ANTHONY EDWARDS",
                typeout1: 'Technology + Innovation',
                typeout2: '2025',
},
        {
                id: 11,
                projectName: 'cc',
                projectNickname: 'CC',
                projectPath: 'assets/MP4/CC.mp4',
                vimeoPath: 'https://player.vimeo.com/video/954469056?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479',
                typeoutName: 'CALIFORNIA CLOSETS 2024',
                typeout1: 'Commercial',
                typeout2: '2024',
},
        {
                id: 12,
                projectName: 'urban',
                projectNickname: 'UD',
                projectPath: 'assets/MP4/UD.mp4',
                vimeoPath: 'https://player.vimeo.com/video/1012646241?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479',
                typeoutName: 'URBAN DECAY MONDIALE',
                typeout1: 'Beauty',
                typeout2: '2024',
},
        {
                id: 13,
                projectName: 'polestar',
                projectNickname: 'POLE',
                projectPath: 'assets/MP4/POLESTAR.mp4',
                vimeoPath: 'https://player.vimeo.com/video/1013672453?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479',
                typeoutName: 'POLESTAR 3 NYC LAUNCH',
                typeout1: 'Event Capture',
                typeout2: '2024',
},
        {
                id: 14,
                projectName: 'reel',
                projectNickname: 'REEL',
                projectPath: 'assets/MP4/REEL.mp4',
                vimeoPath: 'https://player.vimeo.com/video/914863354?h=2af003c63c&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479',
                typeoutName: "REEL",
                typeout1: 'Colorist',
                typeout2: 'Kostadin Kolev',
}]

